// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7zulsAUMA_R-CAbMievIFigLYA0SS2j4',
    appId: '1:161021812024:web:064b1e9cfeadd8131135cd',
    messagingSenderId: '161021812024',
    projectId: 'projetflutterfirebase',
    authDomain: 'projetflutterfirebase.firebaseapp.com',
    storageBucket: 'projetflutterfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOgcC0lQ4sC6sY2VCNRgFKs_Y9amNme1g',
    appId: '1:161021812024:android:f944f1c414a8da8f1135cd',
    messagingSenderId: '161021812024',
    projectId: 'projetflutterfirebase',
    storageBucket: 'projetflutterfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACreMQk5y3f9EotnqpfhoeLM3gJWqjEnw',
    appId: '1:161021812024:ios:512c54819cea244b1135cd',
    messagingSenderId: '161021812024',
    projectId: 'projetflutterfirebase',
    storageBucket: 'projetflutterfirebase.appspot.com',
    iosClientId: '161021812024-utc7f9ho9adh4qv430e9cd3halsr6d42.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetflutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACreMQk5y3f9EotnqpfhoeLM3gJWqjEnw',
    appId: '1:161021812024:ios:512c54819cea244b1135cd',
    messagingSenderId: '161021812024',
    projectId: 'projetflutterfirebase',
    storageBucket: 'projetflutterfirebase.appspot.com',
    iosClientId: '161021812024-utc7f9ho9adh4qv430e9cd3halsr6d42.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetflutterfirebase',
  );
}
